#!/usr/bin/python 
#coding: utf-8 print 
print(" Hola buen dia ")
print("Ponga su numero para contarle")
i=input()

a=0
while (a<i):
       a=a+1
      
       print(a)
       

print("el resultado final es ..." ) 
print(a)
